all: programa
programa: main rectangulo circulo triangulo
	g++ -o a main.o rectangulo.o circulo.o triangulo.o
main: main.cpp
	g++ -c main.cpp
rectangulo: rectangulo.cpp
	g++ -c rectangulo.cpp
circulo: circulo.cpp
	g++ -c circulo.cpp
triangulo: triangulo.cpp
	g++ -c triangulo.cpp